import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import MainNav from '@/components/mainNav'
import MainFooter from '@/components/mainFooter'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=''>

        <MainNav/>
        </div>
       
       <div className='min-h-screen'>

        {children}
       </div>

        <div>
          <MainFooter/>
        </div>
        </body>
    </html>
  )
}
